#install Knative
- name: install knative selector
  command: kubectl apply --selector knative.dev/crd-install=true --filename "{{ item }}"
  with_items: "{{ knative_install }}"
  register: apply_knative
  until: apply_knative.rc == 0
  retries: 10
  delay: 2

#install Knative
- name: install knative filename
  command: kubectl apply --filename "{{ item }}"
  with_items:
    - "{{ knative_install }}"
  register: apply_knative2
  until: apply_knative2.rc == 0
  retries: 10
  delay: 2

#wait for pods to come up
- name: knative - wait for pods to come up
  shell: kubectl -n knative-eventing get pods -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 30
  delay: 10

#wait for pods to come up
- name: knative-serving - wait for pods to come up
  shell: kubectl -n knative-serving get pods -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 30
  delay: 10
